In [39]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [56]:
df = pd.read_csv('D:\ML1BootCamp\Day15_Stock_data_prediction\stock.csv')
df.head()

,last_price,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f153,f154,f155,f156,f157,f158,f159,f160,f161,time
0,43138.2,0.000463,15139,-43.1,43.0,-0.1,-4.8,-5.1,-4.3,-15.2,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:41.916971
1,43138.2,0.000463,15140,-43.1,43.0,-0.1,-4.7,-5.1,-2.4,-15.2,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:40.693372
2,43138.2,0.000463,15141,-37.4,43.0,5.6,-1.9,-0.6,-2.4,-6.7,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:39.968797
3,43138.2,0.000463,15142,-37.4,37.4,0.0,-3.7,-6.2,-10.2,-12.3,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:38.919784
4,43132.6,0.000463,15143,-39.6,36.5,-3.1,-3.7,-9.4,-10.2,-12.4,...,-129.4,689.6,-129.4,-129.4,689.6,689.6,-129.4,-129.4,689.6,12:47:37.881533

In [62]:
df['time'].dtype

dtype('O')

In [61]:
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S.%f').dt.time

In [53]:
df.head()

,last_price,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f153,f154,f155,f156,f157,f158,f159,f160,f161,time
0,43138.2,0.000463,15139,-43.1,43.0,-0.1,-4.8,-5.1,-4.3,-15.2,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:41.916971
1,43138.2,0.000463,15140,-43.1,43.0,-0.1,-4.7,-5.1,-2.4,-15.2,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:40.693372
2,43138.2,0.000463,15141,-37.4,43.0,5.6,-1.9,-0.6,-2.4,-6.7,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:39.968797
3,43138.2,0.000463,15142,-37.4,37.4,0.0,-3.7,-6.2,-10.2,-12.3,...,-123.8,695.2,-123.8,-123.8,695.2,695.2,-123.8,-123.8,695.2,12:47:38.919784
4,43132.6,0.000463,15143,-39.6,36.5,-3.1,-3.7,-9.4,-10.2,-12.4,...,-129.4,689.6,-129.4,-129.4,689.6,689.6,-129.4,-129.4,689.6,12:47:37.881533

In [63]:
X =df.drop(columns=['last_price', 'time'])
X =X[:len(df)-1]
y = df['last_price']
y =y[:len(df)-1]

In [64]:
model = RandomForestRegressor()
model.fit(X,y)

RandomForestRegressor()

In [68]:
pred = model.predict(X)
print(f'Model Score{model.score(X,y)}')

Model Score0.9999988071323156

# Predicting Price of last Record price

In [72]:
newdata = df.drop(columns=['last_price', 'time']).tail(1)
p = model.predict(newdata)
print(f'predicted value {p}')
print(df['last_price'].tail(1))

predicted value [42765.902]
9978    42765.6
Name: last_price, dtype: float64